version: "3.7"
services:

    nginx:
      build:
        context: "."
        dockerfile: ".docker/nginx/Dockerfile"
      restart: "always"
      ports:
        - '8085:80'
      environment:
        - PROJECT_NAME=symvue-cms
        - INDEX_FILE_FOLDER=public
      command: >
        /bin/sh -c
        "envsubst '
        $${PROJECT_NAME}
        $${INDEX_FILE_FOLDER}
        '< /etc/nginx/conf.d/default.conf.template
        > /etc/nginx/conf.d/default.conf
        && nginx -g 'daemon off;'"
      volumes:
        - "./:/var/www"
        - "./.docker/nginx/conf.d:/etc/nginx/conf.d"
        - "./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      links:
        - php-fpm
      networks:
        - "symvueCms"

    php-fpm:
        build:
            context: .
            dockerfile: .docker/php-fpm/Dockerfile
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
             - "symvueCms"

    mysql:
      hostname: symvue-db.local
      image: "mysql:8.0.28"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=symvue_cms
      restart: "always"
      volumes:
        - mysql:/var/lib/mysql
        - ./.docker/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      ports:
        - '3306:3306'
      networks:
        - "symvueCms"

networks:
  symvueCms:
    driver: "bridge"

volumes:
  mysql:
    driver: 'local'
